server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        # Rutas para Usuarios
        - id: msvc-usuario
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/roles/**

        # Rutas para Productos
        - id: msvc-producto
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**, /api/categories/**